language: d
matrix:
    include:
        - d: dmd-2.067.1
        - d: gdc-4.9.2
        - d: ldc-0.15.1
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.14.0
        - d: ldc-0.13.0
        - d: dmd-2.069.2
        - d: dmd-2.071.0